FROM python:3.13

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

# create a group for the user and add the user
RUN if getent group ${GID} >/dev/null; then \
        echo "Group with GID ${GID} already exists, using it."; \
        GROUP_NAME=$(getent group ${GID} | cut -d: -f1); \
    else \
        GROUP_NAME=${USERNAME}; \
        groupadd --gid ${GID} ${GROUP_NAME}; \
    fi && \
    useradd --uid ${UID} --gid ${GID} --create-home --shell /bin/bash ${USERNAME}

WORKDIR /home/${USERNAME}
RUN chown -R ${UID}:${GID} /home/${USERNAME}

# set user
USER ${USERNAME}
CMD ["/bin/bash"]
